<?xml version="1.0" encoding="UTF-8"?>
  <!--太一组作业1-->
<!DOCTYPE movies [

<!ELEMENT movies (movie+)>
<!ELEMENT movie (content,personnel,music,other)>
<!ATTLIST movie  id ID #REQUIRED>
<!ATTLIST movie  Producing_country CDATA #IMPLIED>
<!ELEMENT content (name,synopsis,role)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>

<!ELEMENT role (lead,supporting_role)>
<!ELEMENT lead (#PCDATA)>
<!ATTLIST lead  rolid ID #REQUIRED >
<!ATTLIST lead  rolsex CDATA #IMPLIED >


<!ELEMENT supporting_role (#PCDATA)>
<!ATTLIST supporting_role  suprolid ID #REQUIRED>
<!ATTLIST supporting_role  suprolsex CDATA #IMPLIED>


<!ELEMENT personnel (design,director,performer,other_person)>
<!ELEMENT design (art_design,styling_design,clothing_design)>
<!ELEMENT art_design (#PCDATA)>
<!ELEMENT styling_design (#PCDATA)>
<!ELEMENT clothing_design (#PCDATA)>
<!ELEMENT director (chief_director,other)>
<!ELEMENT chief_director (#PCDATA)>
<!ELEMENT other (corner_director,dubbing_director,deputy_director)>
<!ELEMENT corner_director (#PCDATA)>
<!ELEMENT dubbing_director (#PCDATA)>
<!ELEMENT deputy_director (#PCDATA)>

<!ELEMENT performer (lead,supporting_role)>
<!ELEMENT lead (#PCDATA)>
<!ATTLIST lead  perid ID #REQUIRED>
<!ATTLIST lead  persex CDATA #IMPLIED>
<!ATTLIST lead  pernation CDATA #IMPLIED >

<!ELEMENT supporting_role (#PCDATA)>
<!ATTLIST supporting_role  suprolid ID #REQUIRED>
<!ATTLIST supporting_role  suprolsex CDATA #IMPLIED>
<!ATTLIST supporting_role  suprolnation CDATA #IMPLIED>

<!ELEMENT other_person (sound_recording,photography,screenwriter)>
<!ELEMENT sound_recording (#PCDATA)>
<!ELEMENT photography (#PCDATA)>
<!ELEMENT screenwriter (#PCDATA)>

<!ELEMENT music (theme_song,propaganda_song)>
<!ELEMENT theme_song (#PCDATA)>
<!ATTLIST theme_song  theme_language CDATA #IMPLIED>
<!ATTLIST theme_song  theme_singer CDATA #IMPLIED>

<!ELEMENT propaganda_song (#PCDATA)>
<!ATTLIST propaganda_song  pro_language CDATA #IMPLIED>
<!ATTLIST propaganda_song  pro_singer CDATA #IMPLIED>


<!ELEMENT other (score,release_time,box_office)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT release_time (#PCDATA)>
<!ELEMENT box_office (#PCDATA)>

]>
<movies>
    <movie id="1" Producing_country="USA">
        <content>
	        <name>肖申克的救赎</name>
	        <synopsis>该片改编自斯蒂芬·金《四季奇谭》中收录的同名小说，
	       该片中涵盖全片的主题是“希望”，全片透过监狱这一强制剥夺自由、
	       高度强调纪律的特殊背景来展现作为个体的人对“时间流逝、环境改造”的恐惧。</synopsis>
	        <role>
	            <lead id="1" sex="male" > 安迪·杜佛兰 </lead>
		        <supporting_role id="2" sex="male"> 艾利斯·波德·瑞德 </supporting_role>
		        <supporting_role id="3" sex="male"> 山姆·诺顿 </supporting_role>
		        <supporting_role id="4" sex="male"> 海伍德 </supporting_role>
		        <supporting_role id="5" sex="male"> 拜伦·赫德利 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 彼得·兰斯顿·史密斯 </art_design>
		        <styling_design> 彼得·兰斯顿·史密斯 </styling_design>
                <clothing_design> 伊丽莎白·麦克布莱德 </clothing_design>
            </design>
            <director>
                <chief_director> 弗兰克·德拉邦特 </chief_director>
                <other>
		            <corner_director> 德博拉·阿奎拉 </corner_director>
		            <dubbing_director> 陆揆 </dubbing_director>
                    <deputy_director> 迈克尔·格林伍德 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="USA"> 蒂姆·罗宾斯 </lead>
			    <supporting_role id="2" sex="male" nation="USA"> 摩根·弗里曼 </supporting_role>
		        <supporting_role id="3" sex="male" nation="USA"> 鲍勃·冈顿 </supporting_role>
		        <supporting_role id="4" sex="male" nation="USA"> 威廉姆·赛德勒 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 克兰西·布朗 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 爱德华多·米库奇 </sound_recording>
                <photography> 罗杰·狄金斯 </photography>
                <screenwriter> 斯蒂芬·金 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" pro_singer="The Ink Spots"> 五月 </theme_song>
			<propaganda_song pro_language="English" pro_singer="The Ink Spots"> 肖申克监狱 </propaganda_song>
	    </music>
		<other>
		    <score> 9.6 </score>
            <release_time> 1994-09-10 </release_time>
            <box_office> 28,241,469 </box_office>
		</other>
    </movie>
	
	<movie id="2" Producing_country="CHINA">
        <content>
	        <name>霸王别姬</name>
	        <synopsis>影片围绕两位京剧伶人半个世纪的悲欢离合，展现了对传统文化、人的生存状态及人性的思考与领悟。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 程蝶衣 </lead>
				<lead id="2" sex="male"> 段小楼 </lead>
		        <supporting_role id="3" sex="female"> 菊仙 </supporting_role>
		        <supporting_role id="4" sex="male"> 关师傅 </supporting_role>
		        <supporting_role id="5" sex="male"> 戏园老板 </supporting_role>
		        <supporting_role id="6" sex="male"> 袁四爷 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 陈怀皑 </art_design>
		        <styling_design> 陈怀皑 </styling_design>
                <clothing_design> 陈昌敏 </clothing_design>
            </design>
            <director>
                <chief_director> 陈凯歌 </chief_director>
                <other>
		            <corner_director> 张进战 </corner_director>
		            <dubbing_director> 白玉 </dubbing_director>
                    <deputy_director> 金平 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="CHINA"> 张国荣 </lead>
				<lead id="2" sex="male" nation="CHINA"> 张丰毅 </lead>
			    <supporting_role id="3" sex="female" nation="CHINA"> 巩俐 </supporting_role>
		        <supporting_role id="4" sex="male" nation="CHINA"> 吕齐 </supporting_role>
		        <supporting_role id="5" sex="male" nation="CHINA"> 英达 </supporting_role>
		        <supporting_role id="6" sex="male" nation="CHINA"> 葛优 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 赵季平 </sound_recording>
                <photography> 顾长卫 </photography>
                <screenwriter> 李碧华 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="Chinese" pro_singer="林忆莲"> 当爱已成往事 </theme_song>
			<propaganda_song pro_language="Chinese"> 霸王别姬 </propaganda_song>
	    </music>
		<other>
		    <score> 9.6 </score>
            <release_time> 1993-01-01 </release_time>
            <box_office> 30000000 </box_office>
		</other>
    </movie>
	
	<movie id="3" Producing_country="Britain">
        <content>
	        <name>这个杀手不太冷</name>
	        <synopsis>该片讲述了一名职业杀手莱昂无意间搭救了一个全家被杀害的小女孩玛蒂尔达，他和小女孩互生情愫，最后他为了救玛蒂尔达而身亡的故事。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 莱昂 </lead>
				<lead id="2" sex="female" > 玛蒂尔达 </lead>
		        <supporting_role id="3" sex="male" > 史丹菲尔 </supporting_role>
		        <supporting_role id="4" sex="male" > 托尼 </supporting_role>
		        <supporting_role id="5" sex="male" > 麦基 </supporting_role>
		        <supporting_role id="6" sex="male" > 米基 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 热拉尔德隆 </art_design>
		        <styling_design> 丹·维尔 </styling_design>
                <clothing_design> 玛格丽达吉达斯奇 </clothing_design>
            </design>
            <director>
                <chief_director> 吕克·贝松 </chief_director>
                <other>
		            <corner_director> 托德·泰勒 </corner_director>
		            <dubbing_director> 杰姆斯·布莱德尼 </dubbing_director>
                    <deputy_director> 帕斯卡尔·舒梅 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="Spain"> 让·雷诺 </lead>
				<lead id="2" sex="male" nation="USA"> 娜塔丽·波特曼 </lead>
			    <supporting_role id="3" sex="male" nation="Britain"> 加里·奥德曼 </supporting_role>
		        <supporting_role id="4" sex="male" nation="Britain"> 丹尼·爱罗	 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 彼得·阿佩尔 </supporting_role>
		        <supporting_role id="6" sex="male" nation="USA"> 吕克·伯纳德 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 艾瑞克·塞拉 </sound_recording>
                <photography> 斯艾瑞·阿博贾斯特 </photography>
                <screenwriter> 吕克·贝松 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" > 我心之形 </theme_song>
			<propaganda_song pro_language="English" > 嘿，小天使 </propaganda_song>
	    </music>
		<other>
		    <score> 9.4 </score>
            <release_time> 1994-09-14 </release_time>
            <box_office> 129271500 </box_office>
		</other>
    </movie>
	
	<movie id="4" Producing_country="USA">
        <content>
	        <name>阿甘正传</name>
	        <synopsis>电影改编自美国作家温斯顿·格卢姆于1986年出版的同名小说，
			描绘了先天智障的小镇男孩福瑞斯特·甘自强不息，最终“傻人有傻福”地得到上天眷顾，在多个领域创造奇迹的励志故事。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 阿甘 </lead>
		        <supporting_role id="2" sex="female"> 珍妮·库伦 </supporting_role>
		        <supporting_role id="3" sex="male"> 邓·泰勒 </supporting_role>
		        <supporting_role id="4" sex="female"> 甘普太太 </supporting_role>
		        <supporting_role id="5" sex="male"> 小阿甘 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 莱斯利·麦克唐纳 </art_design>
		        <styling_design> 肯·罗尔斯顿 </styling_design>
                <clothing_design> 乔安娜·约翰斯顿 </clothing_design>
            </design>
            <director>
                <chief_director> 罗伯特·泽米吉斯 </chief_director>
                <other>
		            <corner_director> 艾伦·刘易斯 </corner_director>
		            <dubbing_director> 达纳·库兹涅茨科夫 </dubbing_director>
                    <deputy_director> 谢丽兰·马丁 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="USA"> 汤姆·汉克斯 </lead>
			    <supporting_role id="2" sex="female" nation="USA"> 罗宾·怀特 </supporting_role>
		        <supporting_role id="3" sex="male" nation="USA"> 加里·西尼斯	 </supporting_role>
		        <supporting_role id="4" sex="female" nation="USA"> 莎莉·菲尔德 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 海利·乔·奥斯蒙  </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 亚伦·史维斯查 </sound_recording>
                <photography> 唐·伯吉斯 </photography>
                <screenwriter> 温斯顿·格鲁姆 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English"> 逆风而行 </theme_song>
			<propaganda_song pro_language="English"> 羽毛之歌 </propaganda_song>
	    </music>
		<other>
		    <score> 9.4 </score>
            <release_time> 1994-09-14 </release_time>
            <box_office> 350000000 </box_office>
		</other>
    </movie>
	
	<movie id="5" Producing_country="Italy">
        <content>
	        <name>美丽人生</name>
	        <synopsis>片讲述了一对犹太父子被送进了纳粹集中营，
			父亲利用自己的想像力扯谎说他们正身处一个游戏当中，
			最后父亲让儿子的童心没有受到伤害，而自己却惨死的故事。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 圭多 </lead>
		        <supporting_role id="2" sex="female"> 多拉 </supporting_role>
		        <supporting_role id="3" sex="male"> 乔舒亚 </supporting_role>
		        <supporting_role id="4" sex="male"> 鲁道夫 </supporting_role>
		        <supporting_role id="5" sex="male"> 埃利塞奥奥雷菲斯 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 达尼洛·杜纳蒂</art_design>
		        <styling_design> 路易吉乌尔班尼 </styling_design>
                <clothing_design> 达尼洛·杜纳蒂 </clothing_design>
            </design>
            <director>
                <chief_director> 罗伯托·贝尼尼 </chief_director>
                <other>
		            <corner_director> 谢拉鲁宾 </corner_director>
		            <dubbing_director> 吉安尼·阿杜尼 </dubbing_director>
                    <deputy_director> 丹尼勒卡马 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="Italy"> 罗伯托·贝尼尼 </lead>
			    <supporting_role id="2" sex="female" nation="Italy"> 尼可莱塔·布拉斯基 </supporting_role>
		        <supporting_role id="3" sex="male" nation="Italy"> 乔治·坎塔里尼	 </supporting_role>
		        <supporting_role id="4" sex="male" nation="Italy"> 亚美利哥·方塔尼 </supporting_role>
		        <supporting_role id="5" sex="male" nation="Italy"> 吉乌斯蒂诺·杜兰诺 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 西蒙纳帕吉 </sound_recording>
                <photography> 托尼诺·德尔利·科利 </photography>
                <screenwriter> 罗伯托·贝尼尼 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="Italian" > 早上好公主 </theme_song>
			<propaganda_song pro_language="Italian" > 生命的美丽 </propaganda_song>
	    </music>
		<other>
		    <score> 9.5 </score>
            <release_time> 1997-12-20 </release_time>
            <box_office> 17160000000 </box_office>
		</other>
    </movie>
	
	<movie id="6" Producing_country="USA">
        <content>
	        <name>泰坦尼克号</name>
	        <synopsis>影片以1912年泰坦尼克号邮轮在其处女启航时触礁冰山而
			沉没的事件为背景，讲述了处于不同阶层的两个人穷画家杰克和贵族女露丝
			抛弃世俗的偏见坠入爱河，最终杰克把生命的机会让给了露丝的感人故事。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 杰克 </lead>
				<lead id="2" sex="female"> 露丝 </lead>
		        <supporting_role id="3" sex="male"> 卡尔 </supporting_role>
		        <supporting_role id="4" sex="female"> 老年露丝 </supporting_role>
		        <supporting_role id="5" sex="female"> 莫莉·布朗 </supporting_role>
		        <supporting_role id="6" sex="female"> 露丝德威特丝 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 马丁·莱英 </art_design>
		        <styling_design> 伊莎贝尔阿米祖加 </styling_design>
                <clothing_design> 黛博拉·琳恩·斯科特 </clothing_design>
            </design>
            <director>
                <chief_director> 詹姆斯·卡梅隆 </chief_director>
                <other>
		            <corner_director> 马里-芬 </corner_director>
		            <dubbing_director> 布瑞恩贝克曼 </dubbing_director>
                    <deputy_director> 马丁·兰道 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="USA"> 莱昂纳多·迪卡普里奥 </lead>
				<lead id="2" sex="female" nation="Britain"> 凯特·温斯莱特 </lead>
			    <supporting_role id="3" sex="male" nation="USA"> 比利·赞恩 </supporting_role>
		        <supporting_role id="4" sex="female" nation="USA"> 格劳瑞亚·斯图尔特	 </supporting_role>
		        <supporting_role id="5" sex="female" nation="Britain"> 凯茜·贝茨 </supporting_role>
		        <supporting_role id="5" sex="female" nation="Britain"> 弗兰西丝·费舍 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 詹姆斯·霍纳 </sound_recording>
                <photography> 拉塞尔·卡朋特 </photography>
                <screenwriter> 詹姆斯·卡梅隆 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" > 我心永恒 </theme_song>
			<propaganda_song pro_language="English" > 与主接近 </propaganda_song>
	    </music>
		<other>
		    <score> 9.3 </score>
            <release_time> 1997-12-19 </release_time>
            <box_office> 1816000000 </box_office>
		</other>
    </movie>
	
		<movie id="7" Producing_country="Japan">
        <content>
	        <name >千与千寻</name>
	        <synopsis>该片讲述了少女千寻意外来到神灵异世界后，为了救爸爸妈妈，经历了很多磨难的故事。</synopsis>
	        <role>
	            <lead id="1" sex="female"> 千寻 </lead>
		        <supporting_role id="2" sex="male"> 白龙 </supporting_role>
		        <supporting_role id="3" sex="male"> 无脸男 </supporting_role>
		        <supporting_role id="4" sex="female"> 汤婆婆 </supporting_role>
		        <supporting_role id="5" sex="male"> 荻野明夫 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 武重洋二  </art_design>
		        <styling_design> 诺罗布吉田 </styling_design>
            </design>
            <director>
                <chief_director> 宫崎骏 </chief_director>
                <other>
		            <dubbing_director> 宫崎骏 </dubbing_director>
                    <deputy_director> 高桥寿司 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="female" nation="Japan"> 柊瑠美 </lead>
			    <supporting_role id="2" sex="male" nation="Japan"> 入野自由 </supporting_role>
		        <supporting_role id="3" sex="male" nation="Japan"> 中村彰男 </supporting_role>
		        <supporting_role id="4" sex="female" nation="Japan"> 夏木真理 </supporting_role>
		        <supporting_role id="5" sex="male" nation="Japan"> 内藤刚志 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 林和弘 </sound_recording>
                <photography> 奥井敦 </photography>
                <screenwriter> 宫崎骏 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="Japanese"> 无论多少次 </theme_song>
			<propaganda_song pro_language="Japanese"> 工作好辛苦 </propaganda_song>
	    </music>
		<other>
		    <score> 9.3 </score>
            <release_time> 2001-07-20 </release_time>
            <box_office> 271600000 </box_office>
		</other>
    </movie>
		
	<movie id="8" Producing_country="USA">
        <content>
	        <name>辛德勒的名单</name>
	        <synopsis>影片再现了德国企业家奥斯卡·辛德勒与其夫人埃米莉·辛德勒
			在第二次世界大战期间倾家荡产保护了1200余名犹太人免遭法西斯杀害的真实历史事件。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 奥斯卡·辛德勒 </lead>
		        <supporting_role id="2" sex="male"> 伊兹哈克·斯特恩 </supporting_role>
		        <supporting_role id="3" sex="male"> 阿蒙·高斯 </supporting_role>
		        <supporting_role id="4" sex="female"> 海伦·贺希 </supporting_role>
		        <supporting_role id="5" sex="male"> 谢克 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 艾伦·斯达斯基  </art_design>
			    <styling_design> 史蒂夫普莱斯 </styling_design>
		        <clothing_design> 安娜·谢泼德 </clothing_design>
            </design>
            <director>
                <chief_director> 史蒂文·斯皮尔伯格 </chief_director>
                <other>
				    <corner_director> 托瓦·赛平 </corner_director>
		            <dubbing_director> 马瑞克·布罗德斯基 </dubbing_director>
                    <deputy_director> 塞尔吉奥·米米卡-戈赞 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="Britain"> 连姆·尼森  </lead>
			    <supporting_role id="2" sex="male" nation="Britain"> 本·金斯利 </supporting_role>
		        <supporting_role id="3" sex="male" nation="Britain"> 拉尔夫·费因斯 </supporting_role>
		        <supporting_role id="4" sex="female" nation="USA"> 艾伯丝·戴维兹 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 胡契克·卡勒塔 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 约翰·威廉姆斯 </sound_recording>
                <photography> 贾努兹·卡明斯基 </photography>
                <screenwriter> 斯蒂文·泽里安 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" > 辛德勒名单 </theme_song>
			<propaganda_song pro_language="English" > 我本可以做更多的 </propaganda_song>
	    </music>
		<other>
		    <score> 9.5 </score>
            <release_time> 1993-11-30 </release_time>
            <box_office> 321600000 </box_office>
		</other>
    </movie>
	
	<movie id="9" Producing_country="USA">
        <content>
	        <name>盗梦空间</name>
	        <synopsis>影片讲述由莱昂纳多·迪卡普里奥扮演的造梦师，带领约瑟夫·高登-莱维特、
			艾伦·佩吉扮演的特工团队，进入他人梦境，从他人的潜意识中盗取机密，并重塑他人梦境的故事。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 道姆·柯布 </lead>
		        <supporting_role id="2" sex="female"> 阿丽瑞德妮 </supporting_role>
		        <supporting_role id="3" sex="male"> 亚瑟 </supporting_role>
		        <supporting_role id="4" sex="male"> 伊姆斯 </supporting_role>
		        <supporting_role id="5" sex="female"> 梅尔 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 弗里伯恩  </art_design>
			    <styling_design> 皮特贝布 </styling_design>
		        <clothing_design> 科兰德 </clothing_design>
            </design>
            <director>
                <chief_director> 克里斯托弗·诺兰 </chief_director>
                <other>
				    <corner_director> 约翰·帕帕席德拉 </corner_director>
		            <dubbing_director> 穆罕默德·埃萨吉尔·亚巴赫 </dubbing_director>
                    <deputy_director> 塔里克·艾特·本·阿里 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="5" sex="male" nation="USA"> 莱昂纳多·迪卡普里奥  </lead>
			    <supporting_role id="5" sex="male" nation="USA"> 艾伦·佩姬 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 约瑟夫·高登·莱维特 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 汤姆·哈迪  </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 玛丽昂·歌迪亚 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 汉斯·季默 </sound_recording>
                <photography> 瓦雷·菲斯特 </photography>
                <screenwriter> 克里斯托弗·诺兰 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" > 半梦半醒 </theme_song>
			<propaganda_song pro_language="English" > 梦想破灭 </propaganda_song>
	    </music>
		<other>
		    <score> 9.3 </score>
            <release_time> 2010-09-02 </release_time>
            <box_office> 831600000 </box_office>
		</other>
    </movie>
	
	<movie id="10" Producing_country="USA">
        <content>
	        <name>忠犬八公的故事</name>
	        <synopsis>影片讲述一位大学教授收养了一只小秋田犬，取名“八公”。之后的每天，
			八公早上将教授送到车站，傍晚等待教授一起回家。不幸的是，教授因病辞世，
			再也没有回到车站，然而八公在之后的9年时间里依然每天按时在车站等待，直到最后死去</synopsis>
	        <role>
	            <lead id="1" sex="male"> 帕克 </lead>
		        <supporting_role id="2" sex="female"> 安迪 </supporting_role>
		        <supporting_role id="3" sex="female"> 凯特 </supporting_role>
		        <supporting_role id="4" sex="male"> 卡尔 </supporting_role>
		        <supporting_role id="5" sex="male"> 肯 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 乔丹·雅可布  </art_design>
			    <styling_design> 大卫·伊斯罗明 </styling_design>
		        <clothing_design> 底波拉·纽荷尔 </clothing_design>
            </design>
            <director>
                <chief_director> 莱塞·霍尔斯道姆 </chief_director>
                <other>
				    <corner_director> 里克·蒙哥马利 </corner_director>
		            <dubbing_director> 汤姆·卢斯 </dubbing_director>
                    <deputy_director> 伊丽莎白·麦克斯旺 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="USA"> 理查·基尔  </lead>
			    <supporting_role id="2" sex="female" nation="USA"> 萨拉·罗默尔 </supporting_role>
		        <supporting_role id="3" sex="female" nation="USA"> 琼·艾伦 </supporting_role>
		        <supporting_role id="4" sex="male" nation="Japan"> 田川洋行  </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 凯里-川田博之 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 詹恩.凯兹梅利克 </sound_recording>
                <photography> 罗恩·菲顿纳多 </photography>
                <screenwriter> 史蒂芬·林赛 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" > 舞蹈再现 </theme_song>
			<propaganda_song pro_language="English" > 帕克和八吉 </propaganda_song>
	    </music>
		<other>
		    <score> 9.3 </score>
            <release_time> 2009-08-08 </release_time>
            <box_office> 1365112 </box_office>
		</other>
    </movie>
	
		<movie id="11" Producing_country="USA">
        <content>
	        <name>机器人总动员</name>
	        <synopsis>故事讲述了地球上的清扫型机器人瓦力偶遇并爱上了机器人伊娃后，追随她进入太空历险的一系列故事。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 瓦力 </lead>
		        <supporting_role id="2" sex="female"> 伊娃 </supporting_role>
		        <supporting_role id="3" sex="male"> 弗雷德·维拉德 </supporting_role>
		        <supporting_role id="4" sex="male"> 船长 </supporting_role>
		        <supporting_role id="5" sex="male"> 阿托 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 拉夫·埃格尔斯顿  </art_design>
			    <styling_design> 爱德华·赫什 </styling_design>
            </design>
            <director>
                <chief_director> 安德鲁·斯坦顿 </chief_director>
                <other>
				    <corner_director> 娜塔利·里昂 </corner_director>
		            <dubbing_director> 凯文·雷厄 </dubbing_director>
		        </other>
	        </director>
			<performer>
			    <lead id="5" sex="male" nation="USA"> 本·伯特  </lead>
			    <supporting_role id="5" sex="male" nation="USA"> 艾丽莎·奈特 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 佛莱德·威拉特 </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 杰夫·格尔林  </supporting_role>
		        <supporting_role id="5" sex="male" nation="USA"> 麦金塔 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 托马斯·纽曼 </sound_recording>
                <photography> 斯特芬·斯查福 </photography>
                <screenwriter> 安德鲁·斯坦顿 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" > 凝胶的行军 </theme_song>
			<propaganda_song pro_language="English" > 全息探测 </propaganda_song>
	    </music>
		<other>
		    <score> 9.3 </score>
            <release_time> 2008-06-27 </release_time>
            <box_office> 521311860 </box_office>
		</other>
    </movie>
	
	<movie id="12" Producing_country="India">
        <content>
	        <name>三傻大闹宝莱坞</name>
	        <synopsis>影片采用插叙的手法，讲述了三位主人公法罕、
			拉加与兰彻间的大学故事。兰彻是一个与众不同的大学生，公然顶撞院长，
			并质疑他的教学方法，用智慧打破学院墨守成规的传统教育观念。兰彻的特立独行引起模范学生
			——绰号“消音器”的查尔图的不满，他们约定十年后再一决高下，然而毕业时兰彻却选择了不告而别。
            十年之后，事业有成的“消音器”归来，要兑现当年的诺言，他找来法罕、拉加，一同踏上寻找兰彻的旅程，
            一路上，他们回忆起大学生活的点点滴滴，也发掘出兰彻不为人知的秘密……</synopsis>
	        <role>
	            <lead id="1" sex="male"> 兰彻 </lead>
		        <supporting_role id="2" sex="male"> 法罕 </supporting_role>
		        <supporting_role id="3" sex="male"> 拉加 </supporting_role>
		        <supporting_role id="4" sex="female"> 皮娅 </supporting_role>
		        <supporting_role id="5" sex="male"> 病毒 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 拉金河道  </art_design>
			    <styling_design> 萨米特·巴苏 </styling_design>
		        <clothing_design> 马尼什马尔霍特拉 </clothing_design>
            </design>
            <director>
                <chief_director> 拉库马·希拉尼 </chief_director>
                <other>
				    <corner_director> 米纳卡纳加拉干 </corner_director>
		            <dubbing_director> 马伦迈耶拉格奥 </dubbing_director>
                    <deputy_director> 马赫德德赫隆 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="India"> 阿米尔·汗  </lead>
			    <supporting_role id="2" sex="male" nation="India"> 马德哈万 </supporting_role>
		        <supporting_role id="3" sex="male" nation="India"> 沙尔曼·乔什 </supporting_role>
		        <supporting_role id="4" sex="female" nation="India"> 卡琳娜·卡普  </supporting_role>
		        <supporting_role id="5" sex="male" nation="India"> 博曼·伊拉尼 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 山塔穆特拉 </sound_recording>
                <photography> 摩亨佐·达罗 </photography>
                <screenwriter> 乔普拉 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="Hindi" > 一切顺利 </theme_song>
			<propaganda_song pro_language="Hindi"> 蓝色婚礼 </propaganda_song>
	    </music>
		<other>
		    <score> 9.2 </score>
            <release_time> 2011-12-08 </release_time>
            <box_office> 101887600 </box_office>
		</other>
    </movie>
	
	<movie id="13" Producing_country="Italy">
        <content>
	        <name>海上钢琴师</name>
	        <synopsis>该片改编自亚利桑德罗·巴里克文学剧本《1900：独白》，
			讲述了一个被命名为“1900”的弃婴在一艘远洋客轮上与钢琴结缘，成为钢琴大师的传奇故事。</synopsis>
	        <role>
	            <lead id="1" sex="male"> 1900 </lead>
		        <supporting_role id="2" sex="male"> 马克斯·托尼 </supporting_role>
		        <supporting_role id="3" sex="male"> 丹尼·博德曼 </supporting_role>
		        <supporting_role id="4" sex="male"> 港务长 </supporting_role>
		        <supporting_role id="5" sex="female"> 女孩 </supporting_role>
            </role>
	    </content>
	    <personnel>
	        <design>
	            <art_design> 弗朗西斯科·弗里格利  </art_design>
			    <styling_design> 大卫·布什 </styling_design>
		        <clothing_design> 毛里齐奥·米兰诺提 </clothing_design>
            </design>
            <director>
                <chief_director> 吉赛贝·托纳多雷 </chief_director>
                <other>
				    <corner_director> 法布里齐奥·瑟氏·卡斯泰拉尼 </corner_director>
		            <dubbing_director> 丹佛·贝亚蒂耶 </dubbing_director>
                    <deputy_director> 英迪·卡尔博尼 </deputy_director>
		        </other>
	        </director>
			<performer>
			    <lead id="1" sex="male" nation="Britain"> 蒂姆·罗斯  </lead>
			    <supporting_role id="2" sex="male" nation="USA"> 普路特·泰勒·文斯 </supporting_role>
		        <supporting_role id="3" sex="male" nation="USA"> 比尔·努恩 </supporting_role>
		        <supporting_role id="4" sex="male" nation="USA"> 尼尔·奥布赖恩  </supporting_role>
		        <supporting_role id="5" sex="female" nation="France"> 梅兰尼·蒂埃里 </supporting_role>
            </performer>
		    <other_person>
		        <sound_recording> 埃尼奥·莫里康内 </sound_recording>
                <photography> 拉乔斯·科泰 </photography>
                <screenwriter> 吉赛贝·托纳多雷 </screenwriter>
		    </other_person>
		</personnel>
		<music>
		    <theme_song pro_language="English" > 钢琴家的传奇 </theme_song>
			<propaganda_song pro_language="English" > 弃儿的呼唤 </propaganda_song>
	    </music>
		<other>
		    <score> 9.2 </score>
            <release_time> 1998-10-28 </release_time>
            <box_office> 167435 </box_office>
		</other>
    </movie>
	
		<movie id="14" Producing_country="France">
        <content>
	        <name>放牛班的春天</name>
	        <synopsis>讲述的是一位怀才不遇的音乐老师马修来到辅育院，面对的不是普通学生，